# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sh19-8u10VuD5PIWtL0x4YBZeZntd0t2

# Training a Neural Net Model for Alphabets
"""

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

"""Importing Libraries. Inital try with fastai libraries."""

from fastai import *
from fastai.vision import *
from fastai.metrics import error_rate

# from google.colab import drive
# drive.mount("/content/gdrive")

path = "Data/"


#data = ImageDataBunch.from_name_re(train_path,train_fnames,pat,size=1024,bs=16).normalize(imagenet_stats)
tfms = get_transforms(do_flip=False)
data = ImageDataBunch.from_folder(path,ds_tfms=tfms,size=1024)
# data.show_batch(rows=3)
# plt.show()

learn = cnn_learner(data, models.resnet34, metrics=error_rate)
learn.fit_one_cycle(2)

